### ISSUE TITLE
New Release "1.4.0" with Symfony 6 support

### ISSUE THREAD

**Issue by SebTM** [EugenGanshorn/GuzzleBundleRetryPlugin#14]
Hey, we had to create a fork of the project and tag to install regularly within Symfony 6.x - would love to switch back and delete the fork if we could get a new release here :)

https://github.com/ProtonMail/GuzzleBundleRetryPlugin/releases/tag/1.4.0
Previously requested [here](https://github.com/EugenGanshorn/GuzzleBundleRetryPlugin/pull/12#issuecomment-1751663489)

**Comment by EugenGanshorn** [comment]
released

**Comment by SebTM** [comment]
Thank you 👍🏻
