### ISSUE TITLE
Logger doesn't allow null response

### ISSUE THREAD

**Issue by cavemanlu** [EugenGanshorn/GuzzleBundleRetryPlugin#2]
You already have commit that solve this in 1.1.* version ( https://github.com/EugenGanshorn/GuzzleBundleRetryPlugin/pull/1/commits/d60c9174b2e60fdaa1ad581da74cd0d27703b37a ), but we can't use v1.1 for symfony 4 .
This fix also should be in 1.0.* branch

**Comment by cavemanlu** [comment]
Fixed in https://github.com/EugenGanshorn/GuzzleBundleRetryPlugin/pull/3

**Comment by EugenGanshorn** [comment]
1.2.0 released
